drop table ingredients if exists;
create table ingredients (
		id bigint not null,
		name varchar(50) not null,
		unit varchar(20) not null,
        vegetarian bigint not null,
        vegan bigint not null,
        primary key (id)
);
drop sequence if exists seq_id;
CREATE SEQUENCE seq_id START WITH 1 INCREMENT BY 1;
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Acai', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Ackee', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Apple', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Apricot', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Avocado', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Banana', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Bilberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Blackberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Blackcurrant', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Black sapote', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Blueberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Boysenberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Breadfruit', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Buddha hand', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Cactus pear', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Crab apple', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Currant', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Cherry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Cherimoya', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Chico fruit', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Cloudberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Coconut', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Cranberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Damson', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Date', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Dragonfruit', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Durian', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Elderberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Feijoa', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Fig', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Goji berry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Gooseberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Grape', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Grewia asiatica', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Raisin', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Grapefruit', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Guava', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Hala Fruit', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Honeyberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Huckleberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Jabuticaba', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Jackfruit', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Jambul', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Japanese plum', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Jostaberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Jujube', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Juniper berry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Kiwano (horned melon)', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Kiwifruit', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Kumquat', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Lemon', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Lime', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Loganberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Loquat', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Longan', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Lychee', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Mango', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Mangosteen', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Marionberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Melon', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Cantaloupe', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Galia melon', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Honeydew', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Watermelon', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Miracle fruit', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Monstera Delisiousa', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Mulberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Nectarine', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Nance', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Orange', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Blood orange', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Clementine', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Mandarine', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Tangerine', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Papaya', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Passionfruit', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Peach', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Pear', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Persimmon', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Plantain', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Plum', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Prune', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Pineapple', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Pineberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Plumcot (or Pluot)', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Pomegranate', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Pomelo', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Purple mangosteen', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Quince', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Raspberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Salmonberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Rambutan', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Redcurrant', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Salal berry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Salak', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Satsuma', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Soursop', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Star apple', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Star fruit', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Strawberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Surinam cherry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Tamarillo', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Tamarind', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Tangelo', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Tayberry', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Ugli fruit', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'White currant', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'White sapote', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Yuzu', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Artichoke', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Eggplant', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Asparagus', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Alfalfa sprouts', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Azuki beans', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Bean sprouts', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Black beans', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Black-eyed peas', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Borlotti bean', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Broad beans', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Chickpeas', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Green beans', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Kidney beans', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Lentils', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Lima beans', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Mung beans', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Navy beans', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Peanuts', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Pinto beans', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Runner beans', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Split peas', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Soy beans', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Peas', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Mangetout', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Broccoflower', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Broccoli', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Brussels sprouts', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Cabbage', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Kohlrabi', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Savoy cabbage', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Red cabbage', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Cauliflower', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Celery', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Endive', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Giddleheads', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Grisee', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Gennel', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Nok choy', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Chard', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Collard greens', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Kale', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Mustard greens', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Spinach', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Anise', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Basil', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Caraway', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Coriander', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Chamomile', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Daikon', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Fennel', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Lavender', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Cymbopogon', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Marjoram', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Oregano', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Parsley', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Rosemary', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Sage', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Thyme', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Lettuce', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Mushrooms', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Nettles', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'New Zealand spinach', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Okra', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Chives', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Garlic', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Leek', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Onion', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Shallot', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Scallion', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Bell pepper', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Chili pepper', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Jalapeño', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Habanero', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Paprika', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Tabasco pepper', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Cayenne pepper', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Radicchio', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Rhubarb', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Neetroot', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Mangel-wurzel', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Carrot', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Celeriac', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Eddoe', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Konjac', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Taro', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Water chestnut', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Ginger', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Parsnip', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Rutabaga', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Radish', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Wasabi', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Horseradish', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'White radish', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Diakon', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Jicama', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Jerusalem artichoke', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Potato', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Sweet potato', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Yam', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Turnip', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Salsify', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Skirret', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Sweetcorn', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Topinambur', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Acorn squash', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Nitter melon', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Butternut squash', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Banana squash', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Courgette', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Cucumber', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Delicata', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Gem squash', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Hubbard squash', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Marrow', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Spaghetti squash', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Tat soi', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Tomato', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Watercress', 'kg', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Bear', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Beef', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Beef heart', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Beef liver', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Beef tongue', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Bone soup', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Buffalo', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Calf liver', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Caribou', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Goat', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Ham', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Horse', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Kangaroo', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Lamb', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Marrow soup', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Moose', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Mutton', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Opossum', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Organ Meats', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Pork', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Bacon', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Rabbit', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Snake', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Squirrel', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Sweetbreads', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Tripe', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Turtle', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Veal', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Venison', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Chicken', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Chicken Liver', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Cornish Game Hen', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Duck', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Duck Liver', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Emu', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Gizzards', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Goose', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Goose Liver', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Grouse', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Guinea Hen', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Liver', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Organs', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Ostrich', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Partridge', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Pheasant', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Quail', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Squab', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Turkey', 'kg', 0, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Soy milk', 'l', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Almond milk', 'l', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Skimmed milk', 'l', 1, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Coconut milk', 'l', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Goat milk', 'l', 1, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Rice milk', 'l', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Milk', 'l', 1, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Oat milk', 'l', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Sour cream', 'g', 1, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Butter', 'g', 1, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Ketchup', 'g', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Mustard', 'g', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Mayonnaise', 'g', 1, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Worcestershire sauce', 'g', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'BBQ sauce', 'g', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Lemon juice', 'g', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Tartar sauce', 'g', 1, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Horseradish sauce', 'g', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Cocktail sauce', 'g', 1, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Tabasco sauce', 'g', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Soy sauce', 'g', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Sweet and sour sauce', 'g', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Honey', 'g', 1, 0);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Wine vinegar', 'l', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Balsamic vinegar', 'l', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Olive oil', 'l', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Truffle oil', 'l', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Sesame oil', 'l', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Sugar', 'g', 1, 1);
INSERT INTO ingredients (id, name, unit, vegetarian, vegan) VALUES (seq_id.nextval, 'Salt', 'g', 1, 1);
